### PR TITLE
Support multiple nodes in the local hedera network

### LINKED ISSUE #120: Support multiple nodes in the local hedera network
### Problem

I want to use the hedera local node project for testing. Some of my tests bring down one or more nodes to verify the behavior of my application under those circumstances. I cannot do this on previewnet or testnet. I need to support a multi-node network with control over specific nodes in the network.

### Solution

Add the ability to bring up more than one node, and to alter the status of those nodes. I could use docker commands to stop containers, but it would be better for the command line tool to enable starting and stopping of individual nodes. The "start" command should allow me to specify the number of nodes (perhaps only 1-4 right now is sufficient) and another set of commands should be created to start/stop individual nodes.

### Alternatives

Create a new tool for a multi-node network. I'm not sure the delta between that project and this one is big enough to warrant a completely new tool.

### PR DESCRIPTION
**Pull request by isavov**
**Description**:
This PR adds a new option to the cli tool (`--multinode`) and the necessary docker-compose definitions and additional files to facilitate a multi-node mode with 4 nodes in the network.

* Add docker-compose definitions for multinode mode
* Add needed config files
* Add `--mutlinode` option to cli tool

**Related issue(s)**:

Fixes #120 

**Notes for reviewer**:

**Please note: For this mode Docker needs 14-16 GB of memory**

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by natanasow — APPROVED** [review]
LGTM

**Review by Nana-EC — APPROVED** [review]
LG
Should update the README or add separate documentation to highlight the capabilities and limitations of the multi node

**Comment by isavov** [comment]
> LG Should update the README or add separate documentation to highlight the capabilities and limitations of the multi node

There is issue #317 to address the need for documentation

**Review by georgi-l95 — APPROVED** [review]
Nice improvement.

**Comment by lainhathoang** [comment]
Hi, Is there any documentation for setting up multiple local nodes?

**Comment by georgi-l95** [comment]
Hey @lainhathoang currently no and multi node mode is at no working state at the moment, we have an issue for this in our backlog, you can track it [here](https://github.com/hashgraph/hedera-local-node/issues/436) and [here](https://github.com/hashgraph/hedera-local-node/issues/317)

**Pull request merged**
