### PR TITLE
Added host option for cli.js

### PR DESCRIPTION
**Pull request by sergioaiobuilders**
**Description**:
Adds a `--host`option for the cli.js

**Related issue(s)**:

Issue # 136 (Q&A)
https://github.com/hashgraph/hedera-local-node/discussions/136

### CODE REVIEW

**Comment by Kalina-Todorova** [comment]
Hi @sergioaiobuilders thanks for opening this PR, could you sign your commit and resolve the conflicts in order for us to be able to merge it?

**Comment by sergioaiobuilders** [comment]
Sure I'll update it as soon as i can.

**Comment by sergioaiobuilders** [comment]
> Hi @sergioaiobuilders thanks for opening this PR, could you sign your commit and resolve the conflicts in order for us to be able to merge it?

I've updated the PR with signed commits and the chages from main

**Review by georgi-l95 — CHANGES_REQUESTED** [review]
LG, just please edit README file to reflect those changes.

**Review by georgi-l95 — APPROVED** [review]
LGTM

**Pull request merged**
